import * as Types from '../types/learningOS';

export const seedProblems: Types.Problem[] = [
  // --- Two Pointers ---
  {
    id: 'prob-two-sum-ii',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Pair with Target Sum (Two Sum II)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/',
    difficulty: 'Easy',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-rearrange-0-1',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Rearrange 0 and 1 (Segregate 0s and 1s)',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/segregate-0s-and-1s5106/1',
    difficulty: 'Easy',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-duplicates-list',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Remove Duplicates from Sorted List',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/',
    difficulty: 'Easy',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-duplicates-array',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Remove Duplicates from Sorted Array',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/',
    difficulty: 'Easy',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-duplicates-array-ii',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Remove Duplicates from Sorted Array II',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-squares-sorted-array',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Squaring a Sorted Array',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/squares-of-a-sorted-array/',
    difficulty: 'Easy',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-3sum',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Triplet Sum to Zero (3Sum)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/3sum/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-3sum-closest',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Triplet Sum Close to Target (3Sum Closest)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/3sum-closest/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-triplets-smaller-sum',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Triplets with Smaller Sum',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/count-triplets-with-sum-smaller-than-x5549/1',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-subarray-product-less-than-k',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Subarrays with Product Less than a Target',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/subarray-product-less-than-k/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-dutch-national-flag',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Dutch National Flag Problem (Sort Colors)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/sort-colors/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-4sum',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Quadruple Sum to Target (4Sum)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/4sum/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-backspace-compare',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Comparing Strings containing Backspaces',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/backspace-string-compare/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-shortest-unsorted-subarray',
    subtopicId: 'sub-arr-two-pointers',
    title: 'Minimum Window Sort (Shortest Unsorted Subarray)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/shortest-unsorted-continuous-subarray/',
    difficulty: 'Medium',
    pattern: 'Pattern: Two Pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Fast & Slow Pointers (Linked List & General) ---
  {
    id: 'prob-linked-list-cycle',
    subtopicId: 'sub-ll-fast-slow',
    title: 'LinkedList Cycle',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/linked-list-cycle/',
    difficulty: 'Easy',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-linked-list-cycle-ii',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Start of LinkedList Cycle (II)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/linked-list-cycle-ii/',
    difficulty: 'Medium',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-happy-number',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Happy Number',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/happy-number/',
    difficulty: 'Medium',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-duplicate-number',
    subtopicId: 'sub-ll-fast-slow',
    title: 'FIND DUPLICATE NUMBER',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-the-duplicate-number/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-middle-linked-list',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Middle of the LinkedList',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    difficulty: 'Easy',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-palindrome-linked-list',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Palindrome LinkedList',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/palindrome-linked-list/',
    difficulty: 'Medium',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reorder-list',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Rearrange a LinkedList (Reorder List)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reorder-list/',
    difficulty: 'Medium',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-circular-array-loop',
    subtopicId: 'sub-ll-fast-slow',
    title: 'Cycle in a Circular Array (Circular Array Loop)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/circular-array-loop/',
    difficulty: 'Hard',
    pattern: 'Pattern: Fast & Slow pointers',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Sliding Window ---
  {
    id: 'prob-max-sum-subarray-k',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Maximum Sum Subarray of Size K',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/max-sum-subarray-of-size-k5313/1',
    difficulty: 'Easy',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-min-size-subarray-sum',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Smallest Subarray with a given sum (Minimum Size Subarray Sum)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
    difficulty: 'Easy',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-substring-k-distinct',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Longest Substring with K Distinct Characters',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1',
    difficulty: 'Medium',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-fruit-into-baskets',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Fruits into Baskets',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/fruit-into-baskets/',
    difficulty: 'Medium',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-substring-without-repeating',
    subtopicId: 'sub-arr-sliding-window',
    title: 'No-repeat Substring (Longest Substring Without Repeating Characters)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-repeating-replacement',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Longest Substring with Same Letters after Replacement',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-consecutive-ones-iii',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Longest Subarray with Ones after Replacement (Max Consecutive Ones III)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/max-consecutive-ones-iii/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-minimum-window-substring',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Minimum Size Substring (Minimum Window Substring)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-window-substring/description/?envType=study-plan-v2&envId=top-interview-150',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-permutation-in-string',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Permutation in a String',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/permutation-in-string/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-all-anagrams',
    subtopicId: 'sub-arr-sliding-window',
    title: 'String Anagrams (Find All Anagrams in a String)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-substring-concatenation',
    subtopicId: 'sub-arr-sliding-window',
    title: 'Words Concatenation (Substring with Concatenation of All Words)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',
    difficulty: 'Hard',
    pattern: 'Pattern: Sliding Window',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Kadane Pattern ---
  {
    id: 'prob-max-subarray-kadane',
    subtopicId: 'sub-arr-kadane',
    title: 'Maximum Subarray Sum',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-subarray/?utm_source=chatgpt.com',
    difficulty: 'Medium',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-min-subarray-sum',
    subtopicId: 'sub-arr-kadane',
    title: 'Minimum Subarray Sum',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/smallest-sum-contiguous-subarray/1',
    difficulty: 'Easy',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-product-subarray',
    subtopicId: 'sub-arr-kadane',
    title: 'Maximum Product Subarray',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-product-subarray/?utm_source=chatgpt.com',
    difficulty: 'Medium',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-subarray-one-deletion',
    subtopicId: 'sub-arr-kadane',
    title: 'Maximum Subarray Sum with One Deletion',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-absolute-sum-subarray',
    subtopicId: 'sub-arr-kadane',
    title: 'Maximum Absolute Sum of Any Subarray',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-absolute-sum-of-any-subarray/',
    difficulty: 'Medium',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-sum-circular-subarray',
    subtopicId: 'sub-arr-kadane',
    title: 'Maximum Sum in Circular Array Variant (Maximum Sum Circular Subarray)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-sum-circular-subarray/?utm_source=chatgpt.com',
    difficulty: 'Medium',
    pattern: 'Pattern: Kadane pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Prefix Sum ---
  {
    id: 'prob-subarray-sum-equals-k',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Subarray Sum Equals K',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/subarray-sum-equals-k/description/',
    difficulty: 'Easy',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-pivot-index',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Find Pivot Index',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-pivot-index/description/',
    difficulty: 'Easy',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-subarray-sums-divisible-k',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Subarray Sums Divisible By K',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/subarray-sums-divisible-by-k/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-contiguous-array',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Contiguous array',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/contiguous-array/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-shortest-subarray-sum-at-least-k',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Shortest Subarray With Sum at Least K',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/description/',
    difficulty: 'Hard',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-count-range-sum',
    subtopicId: 'sub-arr-prefix-sum',
    title: 'Count Range Sum',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/count-of-range-sum/description/',
    difficulty: 'Hard',
    pattern: 'Pattern: Prefix Sum',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Merge Intervals ---
  {
    id: 'prob-merge-intervals',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Merge Intervals',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/merge-intervals/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-insert-interval',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Insert Interval',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/insert-interval/',
    difficulty: 'Medium',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-interval-list-intersections',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Intervals Intersection',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/interval-list-intersections/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-overlapping-intervals',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Overlapping Intervals',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/check-if-any-two-intervals-overlap-among-a-given-set-of-intervals/',
    difficulty: 'Medium',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-minimum-meeting-rooms',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Minimum Meeting Rooms',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/attend-all-meetings-ii/1',
    difficulty: 'Hard',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-maximum-cpu-load',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Maximum CPU Load',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/maximum-cpu-load-from-the-given-list-of-jobs/',
    difficulty: 'Hard',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-employee-free-time',
    subtopicId: 'sub-arr-merge-intervals',
    title: 'Employee Free Time',
    platform: 'Custom',
    link: 'https://www.codertrain.co/employee-free-time',
    difficulty: 'Hard',
    pattern: 'Pattern: Merge Intervals',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- In-place Reversal of a LinkedList ---
  {
    id: 'prob-reverse-linked-list',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Reverse a LinkedList',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reverse-linked-list/',
    difficulty: 'Easy',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reverse-linked-list-ii',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Reverse a Sub-list (Reverse Linked List II)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reverse-linked-list-ii/',
    difficulty: 'Medium',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-swap-nodes-in-pairs',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Reverse List in Pairs (Swap Nodes in Pairs)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/swap-nodes-in-pairs/description/',
    difficulty: 'Medium',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reverse-nodes-k-group',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Reverse every K-element Sub-list (Reverse Nodes in K-Group)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    difficulty: 'Hard',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reverse-nodes-even-length-groups',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Reverse nodes in EVEN Length Groups',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reverse-nodes-even-length-groups/description/',
    difficulty: 'Hard',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-rotate-list',
    subtopicId: 'sub-ll-in-place-reversal',
    title: 'Rotate a LinkedList (Rotate List)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/rotate-list/',
    difficulty: 'Medium',
    pattern: 'Pattern: In-place Reversal of a LinkedList',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Stack ---
  {
    id: 'prob-remove-adjacent-duplicates-string',
    subtopicId: 'sub-stack-core',
    title: 'remove adjacent duplicates',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/description/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-valid-parentheses',
    subtopicId: 'sub-stack-core',
    title: 'Balanced Parentheses (Valid Parentheses)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/valid-parentheses/description/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reverse-string',
    subtopicId: 'sub-stack-core',
    title: 'Reverse a String',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reverse-string/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-next-greater-element-ii',
    subtopicId: 'sub-stack-core',
    title: 'Next Greater Element',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/next-greater-element-ii/description/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-daily-temperatures',
    subtopicId: 'sub-stack-core',
    title: 'Daily Temperatures',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/daily-temperatures/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-nodes-linked-list',
    subtopicId: 'sub-stack-core',
    title: 'Remove Nodes From Linked List',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-nodes-from-linked-list/',
    difficulty: 'Easy',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-adjacent-duplicates-ii',
    subtopicId: 'sub-stack-core',
    title: 'Remove All Adjacent Duplicates in String II',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/',
    difficulty: 'Medium',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-simplify-path',
    subtopicId: 'sub-stack-core',
    title: 'Simplify Path',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/simplify-path/',
    difficulty: 'Medium',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-k-digits',
    subtopicId: 'sub-stack-core',
    title: 'Remove K Digits',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/remove-k-digits/',
    difficulty: 'Hard',
    pattern: 'Stack',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Hash Maps ---
  {
    id: 'prob-first-uniq-char',
    subtopicId: 'sub-hashmaps-core',
    title: 'First Non-repeating Character',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/first-unique-character-in-a-string/',
    difficulty: 'Easy',
    pattern: 'Hash Maps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-balloons',
    subtopicId: 'sub-hashmaps-core',
    title: 'Maximum Number of Balloons',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-number-of-balloons/',
    difficulty: 'Easy',
    pattern: 'Hash Maps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-palindrome',
    subtopicId: 'sub-hashmaps-core',
    title: 'Longest Palindrome',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/longest-palindrome/',
    difficulty: 'Easy',
    pattern: 'Hash Maps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-ransom-note',
    subtopicId: 'sub-hashmaps-core',
    title: 'Ransom Note',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/ransom-note/',
    difficulty: 'Easy',
    pattern: 'Hash Maps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },

  // --- Binary Search ---
  {
    id: 'prob-binary-search-basic',
    subtopicId: 'sub-bs-core',
    title: 'Binary search basic',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-search/',
    difficulty: 'Easy',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-ceil-sorted-array',
    subtopicId: 'sub-bs-core',
    title: 'Upper Bound/ Ceiling',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/ceil-in-a-sorted-array/1',
    difficulty: 'Easy',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-first-last-position',
    subtopicId: 'sub-bs-core',
    title: 'First and Last position (Find First and Last Position of Element in Sorted Array)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-number-of-occurrence',
    subtopicId: 'sub-bs-core',
    title: 'Count number of occurences',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-position-infinite-array',
    subtopicId: 'sub-bs-core',
    title: 'Search in infinite Sorted array',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/find-position-element-sorted-array-infinite-numbers/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-peak-index-mountain',
    subtopicId: 'sub-bs-core',
    title: 'Peak index in Mountain',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/',
    difficulty: 'Easy',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-peak-element',
    subtopicId: 'sub-bs-core',
    title: 'Find peak in mountain range (Find Peak Element)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-peak-element/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-minimum-rotated-array',
    subtopicId: 'sub-bs-core',
    title: 'Find minimum in rotated sorted array',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-rotation-count',
    subtopicId: 'sub-bs-core',
    title: 'Find number of rotations to sorted array',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/rotation4723/1',
    difficulty: 'Easy',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-search-rotated-array',
    subtopicId: 'sub-bs-core',
    title: 'Search in rotated sorted array',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/description/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-koko-eating-bananas',
    subtopicId: 'sub-bs-core',
    title: 'KOKO eating BANANAS',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/koko-eating-bananas/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-min-days-bouquets',
    subtopicId: 'sub-bs-core',
    title: 'Min num of days to make m bouquets',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-aggressive-cows',
    subtopicId: 'sub-bs-core',
    title: 'Aggresive cows',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/aggressive-cows/1',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-h-index-ii',
    subtopicId: 'sub-bs-core',
    title: 'H index 2',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/h-index-ii/description/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-max-candies-allocated',
    subtopicId: 'sub-bs-core',
    title: 'Max candies to k children',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-candies-allocated-to-k-children/description/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-capacity-ship-packages',
    subtopicId: 'sub-bs-core',
    title: 'Capacity to ship packages in d days',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/description/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-book-allocation',
    subtopicId: 'sub-bs-core',
    title: 'Book Allocation Problem',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1',
    difficulty: 'Hard',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-split-array-largest-sum',
    subtopicId: 'sub-bs-core',
    title: 'Split largest arrray',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/split-array-largest-sum/description/',
    difficulty: 'Hard',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-search-2d-matrix',
    subtopicId: 'sub-bs-core',
    title: 'Search 2 D matrix',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/search-a-2d-matrix/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-search-2d-matrix-ii',
    subtopicId: 'sub-bs-core',
    title: 'Search 2D matrix (Hard)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/search-a-2d-matrix-ii/description/',
    difficulty: 'Hard',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-kth-smallest-sorted-matrix',
    subtopicId: 'sub-bs-core',
    title: 'kth smallest in sorted matrix',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/',
    difficulty: 'Medium',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-kth-smallest-multiplication-table',
    subtopicId: 'sub-bs-core',
    title: 'kth smallest in multiplication matrix',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/description/',
    difficulty: 'Hard',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-median-two-sorted-arrays',
    subtopicId: 'sub-bs-core',
    title: 'median of 2 sorted arrays',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    difficulty: 'Hard',
    pattern: 'Binary Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Heap Pattern: 1. Kth ---
  {
    id: 'prob-kth-smallest-heap',
    subtopicId: 'sub-heap-kth',
    title: 'kth smallest',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/kth-smallest-element5635/1',
    difficulty: 'Easy',
    pattern: 'Heap Pattern: 1. Kth',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-kth-largest-array',
    subtopicId: 'sub-heap-kth',
    title: 'kth largest',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 1. Kth',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-top-k-frequent-elements',
    subtopicId: 'sub-heap-kth',
    title: 'TOP K frequent Elements',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/top-k-frequent-elements/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 1. Kth',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-top-k-frequent-words',
    subtopicId: 'sub-heap-kth',
    title: 'Top K frequent Words',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/top-k-frequent-words/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 1. Kth',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Heap Pattern: 2. K closest ---
  {
    id: 'prob-k-closest-points-origin',
    subtopicId: 'sub-heap-k-closest',
    title: 'K closest points to origin',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/k-closest-points-to-origin/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 2. K closest',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-find-k-closest-elements',
    subtopicId: 'sub-heap-k-closest',
    title: 'Find K closest elements',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-k-closest-elements/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 2. K closest',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-k-weakest-rows',
    subtopicId: 'sub-heap-k-closest',
    title: 'Kth weakest row in Matrix',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/description/',
    difficulty: 'Easy',
    pattern: 'Heap Pattern: 2. K closest',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },

  // --- Heap Pattern: 3. heap as pointer ---
  {
    id: 'prob-merge-k-sorted-arrays',
    subtopicId: 'sub-heap-as-pointer',
    title: 'Merge K Sorted Arrays',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/merge-k-sorted-arrays/1',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 3. heap as pointer',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-kth-smallest-sorted-matrix-heap',
    subtopicId: 'sub-heap-as-pointer',
    title: 'Kth Smallest in Sorted Matrix',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 3. heap as pointer',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Heap Pattern: 4. GREEDY+heap ---
  {
    id: 'prob-last-stone-weight',
    subtopicId: 'sub-heap-greedy',
    title: 'LAST STONE WEIGHT',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/last-stone-weight/description/',
    difficulty: 'Easy',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-task-scheduler',
    subtopicId: 'sub-heap-greedy',
    title: 'CPU Task Scheduler',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/task-scheduler/description/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-reorganize-string',
    subtopicId: 'sub-heap-greedy',
    title: 'Reorganize String',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/reorganize-string/',
    difficulty: 'Medium',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-min-refueling-stops',
    subtopicId: 'sub-heap-greedy',
    title: 'Min number of refueling stops',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-number-of-refueling-stops/description/',
    difficulty: 'Hard',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-ipo',
    subtopicId: 'sub-heap-greedy',
    title: 'IPO',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/ipo/description/',
    difficulty: 'Hard',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-course-schedule-iii',
    subtopicId: 'sub-heap-greedy',
    title: 'Course Scheduler 3',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/course-schedule-iii/description/',
    difficulty: 'Hard',
    pattern: 'Heap Pattern: 4. GREEDY+heap',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Heap Pattern: 5. 2 heaps ---
  {
    id: 'prob-find-median-data-stream',
    subtopicId: 'sub-heap-2-heaps',
    title: 'Find median in data stream',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/find-median-from-data-stream/description/',
    difficulty: 'Hard',
    pattern: 'Heap Pattern: 5. 2 heaps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-sliding-window-median',
    subtopicId: 'sub-heap-2-heaps',
    title: 'Sliding Window Median',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/sliding-window-median/description/',
    difficulty: 'Hard',
    pattern: 'Heap Pattern: 5. 2 heaps',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Recursion and Backtracking ---
  {
    id: 'prob-fibonacci-recursion',
    subtopicId: 'sub-recursion-core',
    title: 'Fibonnaci',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/fibonacci-number/description/',
    difficulty: 'Easy',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-palindrome-string',
    subtopicId: 'sub-recursion-core',
    title: 'Check if string is Pallindrome',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/palindrome-string0817/1',
    difficulty: 'Easy',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-array-sorted',
    subtopicId: 'sub-recursion-core',
    title: 'Check if Array is Sorted',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1',
    difficulty: 'Easy',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-sum-of-digits',
    subtopicId: 'sub-recursion-core',
    title: 'Sum of digits of a number',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/sum-of-digits1742/1',
    difficulty: 'Easy',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-remove-char-recursion',
    subtopicId: 'sub-recursion-core',
    title: 'Remove occurences of a character in string',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/remove-all-occurrences-of-a-character-in-a-string/1',
    difficulty: 'Easy',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-generate-parentheses',
    subtopicId: 'sub-recursion-core',
    title: 'Generate parenthesis',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/generate-parentheses/description/',
    difficulty: 'Medium',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-letter-combinations-phone',
    subtopicId: 'sub-recursion-core',
    title: 'Letter Combinations of phone number',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/',
    difficulty: 'Medium',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-permutations',
    subtopicId: 'sub-recursion-core',
    title: 'Permutations',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/permutations/description/',
    difficulty: 'Medium',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-combination-sum',
    subtopicId: 'sub-recursion-core',
    title: 'Combination Sum',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/combination-sum/description/',
    difficulty: 'Medium',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-palindrome-partitioning',
    subtopicId: 'sub-recursion-core',
    title: 'Pallindrome partition',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/palindrome-partitioning/description/',
    difficulty: 'Medium',
    pattern: 'Recursion and Backtracking Pattern',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 1. Traversal ---
  {
    id: 'prob-tree-inorder-traversal',
    subtopicId: 'sub-tree-traversal',
    title: 'Inorder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-inorder-traversal/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-tree-preorder-traversal',
    subtopicId: 'sub-tree-traversal',
    title: 'Preorder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-preorder-traversal/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-tree-postorder-traversal',
    subtopicId: 'sub-tree-traversal',
    title: 'Postorder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-postorder-traversal/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-tree-level-order-traversal',
    subtopicId: 'sub-tree-traversal',
    title: 'Level Order',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-tree-zigzag-level-order',
    subtopicId: 'sub-tree-traversal',
    title: 'ZigZag Order',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-tree-level-order-ii',
    subtopicId: 'sub-tree-traversal',
    title: 'Level Order II',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-level-order-traversal-ii/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 1. Traversal',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 2. Mirror and Symmetry ---
  {
    id: 'prob-invert-binary-tree',
    subtopicId: 'sub-tree-mirror',
    title: 'Invert Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/invert-binary-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 2. Mirror and Symmetry',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-symmetric-tree',
    subtopicId: 'sub-tree-mirror',
    title: 'Symmetric Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/symmetric-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 2. Mirror and Symmetry',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-same-tree',
    subtopicId: 'sub-tree-mirror',
    title: 'Same Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/same-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 2. Mirror and Symmetry',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 10,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-subtree-another-tree',
    subtopicId: 'sub-tree-mirror',
    title: 'Subtree of another TREE',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/subtree-of-another-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 2. Mirror and Symmetry',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-flip-equivalent-tree',
    subtopicId: 'sub-tree-mirror',
    title: 'Flip Equivalent Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/flip-equivalent-binary-trees/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 2. Mirror and Symmetry',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 3. Search ---
  {
    id: 'prob-lowest-common-ancestor-binary-tree',
    subtopicId: 'sub-tree-search',
    title: 'LCA of Binary TREE',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-search-bst',
    subtopicId: 'sub-tree-search',
    title: 'Binary Search Tree (Search Node)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/search-in-a-binary-search-tree/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-lowest-common-ancestor-bst',
    subtopicId: 'sub-tree-search',
    title: 'LCA of BST',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-lca-deepest-leaves',
    subtopicId: 'sub-tree-search',
    title: 'LCA of Deepest Leaves',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-deepest-leaves/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-two-sum-iv-bst',
    subtopicId: 'sub-tree-search',
    title: 'Two Sum IV (BST variant)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-kth-smallest-element-bst',
    subtopicId: 'sub-tree-search',
    title: 'Kth smallest element in BST',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 3. Search',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 4. Validation ---
  {
    id: 'prob-minimum-depth-binary-tree',
    subtopicId: 'sub-tree-validation',
    title: 'Minimum Depth of Binary Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-maximum-depth-binary-tree',
    subtopicId: 'sub-tree-validation',
    title: 'Maximum Depth of Binary Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-balanced-binary-tree',
    subtopicId: 'sub-tree-validation',
    title: 'Balanced Binary Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/balanced-binary-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-diameter-binary-tree',
    subtopicId: 'sub-tree-validation',
    title: 'Diameter of Binary Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/diameter-of-binary-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-check-completeness-binary-tree',
    subtopicId: 'sub-tree-validation',
    title: 'Check Completeness of Binary Tree',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/check-completeness-of-a-binary-tree/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-validate-bst',
    subtopicId: 'sub-tree-validation',
    title: 'Validate BST',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/validate-binary-search-tree/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-recover-bst',
    subtopicId: 'sub-tree-validation',
    title: 'Recover BST',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/recover-binary-search-tree/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 4. Validation',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 5. Path SUM ---
  {
    id: 'prob-path-sum',
    subtopicId: 'sub-tree-path-sum',
    title: 'Path Sum',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/path-sum/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 5. Path SUM',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-path-sum-ii',
    subtopicId: 'sub-tree-path-sum',
    title: 'Path Sum II',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/path-sum-ii/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 5. Path SUM',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-sum-root-to-leaf',
    subtopicId: 'sub-tree-path-sum',
    title: 'Sum of Root to Leaf',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/sum-root-to-leaf-numbers/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 5. Path SUM',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-binary-tree-maximum-path-sum',
    subtopicId: 'sub-tree-path-sum',
    title: 'Maximum Path Sum',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/description/',
    difficulty: 'Hard',
    pattern: 'Tree Pattern: 5. Path SUM',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- Tree Pattern: 6. Construction ---
  {
    id: 'prob-construct-tree-preorder-inorder',
    subtopicId: 'sub-tree-construction',
    title: 'Contruct tree from preorder and inorder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 6. Construction',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-construct-tree-inorder-postorder',
    subtopicId: 'sub-tree-construction',
    title: 'Contruct tree from postorder and inorder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/description/',
    difficulty: 'Medium',
    pattern: 'Tree Pattern: 6. Construction',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-convert-sorted-array-to-bst',
    subtopicId: 'sub-tree-construction',
    title: 'Sorted Array to BST',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/',
    difficulty: 'Easy',
    pattern: 'Tree Pattern: 6. Construction',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },

  // --- GRAPHS ---
  {
    id: 'prob-print-adjacency-list',
    subtopicId: 'sub-graphs-core',
    title: 'Construct Adjancency List from EDGES+Nodes',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/print-adjacency-list-1587115620/1',
    difficulty: 'Easy',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-graph-dfs',
    subtopicId: 'sub-graphs-core',
    title: 'Graph DFS',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1',
    difficulty: 'Easy',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-graph-bfs',
    subtopicId: 'sub-graphs-core',
    title: 'GRAPH BFS',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1',
    difficulty: 'Easy',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-number-islands',
    subtopicId: 'sub-graphs-core',
    title: 'Number of Islands',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/number-of-islands/description/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-number-provinces',
    subtopicId: 'sub-graphs-core',
    title: 'Number of Provinces',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/number-of-provinces/description/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-rotting-oranges',
    subtopicId: 'sub-graphs-core',
    title: 'Rotten Oranges',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/rotting-oranges/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-detect-cycle-undirected-graph',
    subtopicId: 'sub-graphs-core',
    title: 'Cycle detection in undirected graph',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-detect-cycle-directed-graph',
    subtopicId: 'sub-graphs-core',
    title: 'Cycle detection in directed graph',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-topological-sort',
    subtopicId: 'sub-graphs-core',
    title: 'Topological sort',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/topological-sort/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-is-graph-bipartite',
    subtopicId: 'sub-graphs-core',
    title: 'Bipartite Graph/ Graph Coloring',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/is-graph-bipartite/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-surrounded-regions',
    subtopicId: 'sub-graphs-core',
    title: 'Surrounded Regoins',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/surrounded-regions/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-shortest-path-undirected-graph',
    subtopicId: 'sub-graphs-core',
    title: 'Shortest Path in Non-Weighted Graph',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/shortest-path-in-undirected-graph-having-unit-distance/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-dijkstra-adjacency-matrix',
    subtopicId: 'sub-graphs-core',
    title: "Dijkstra's Algorithm",
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-network-delay-time',
    subtopicId: 'sub-graphs-core',
    title: 'Network Delay',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/network-delay-time/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-path-with-minimum-effort',
    subtopicId: 'sub-graphs-core',
    title: 'Path With Minimum Effort',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/path-with-minimum-effort/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-swim-in-rising-water',
    subtopicId: 'sub-graphs-core',
    title: 'Swim in Rising Water',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/swim-in-rising-water/',
    difficulty: 'Hard',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-bellman-ford',
    subtopicId: 'sub-graphs-core',
    title: 'Bellman ford',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-cheapest-flights-within-k-stops',
    subtopicId: 'sub-graphs-core',
    title: 'Cheapest Path in K stops',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/description/',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-minimum-spanning-tree',
    subtopicId: 'sub-graphs-core',
    title: 'Prim MST',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1',
    difficulty: 'Medium',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-word-ladder',
    subtopicId: 'sub-graphs-core',
    title: 'Word Ladder',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/word-ladder/',
    difficulty: 'Hard',
    pattern: 'GRAPHS',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  },

  // --- DP (Dynamic Programming) ---
  {
    id: 'prob-fibonacci-dp',
    subtopicId: 'sub-dp-core',
    title: 'Episode-02: Fibonacci',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/fibonacci-number/description/',
    difficulty: 'Easy',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 12,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-climbing-stairs-dp',
    subtopicId: 'sub-dp-core',
    title: 'Episode 03: Climbing Stairs',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/climbing-stairs/description/',
    difficulty: 'Easy',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-house-robber',
    subtopicId: 'sub-dp-core',
    title: 'Episode 04: House Robber',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/house-robber/',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-knapsack-01-memo',
    subtopicId: 'sub-dp-core',
    title: 'Episode 05: 0/1 Knapsack',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-knapsack-01-tab',
    subtopicId: 'sub-dp-core',
    title: 'Episode 07: 0/1 Knapsack Tabulation',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-subset-sum-problem',
    subtopicId: 'sub-dp-core',
    title: 'Episode 08: Subset sum',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-target-sum-dp',
    subtopicId: 'sub-dp-core',
    title: 'Episode 09 : Target Sum',
    platform: 'GFG',
    link: 'https://www.geeksforgeeks.org/problems/target-sum-1626326450/1',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-increasing-subsequence',
    subtopicId: 'sub-dp-core',
    title: 'Episode 10 : LIS',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-longest-common-subsequence',
    subtopicId: 'sub-dp-core',
    title: 'Episode 12 : LCS',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/longest-common-subsequence/description/',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 25,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-unique-paths',
    subtopicId: 'sub-dp-core',
    title: 'Episode 13 : Unique Paths',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/unique-paths/description/',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-best-time-buy-sell-stock',
    subtopicId: 'sub-dp-core',
    title: 'Episode 14: Buy Sell Stocks (I)',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/',
    difficulty: 'Easy',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 15,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-best-time-buy-sell-stock-ii',
    subtopicId: 'sub-dp-core',
    title: 'Episode 14: Buy Sell Stocks II',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/description/',
    difficulty: 'Medium',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 20,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-best-time-buy-sell-stock-iii',
    subtopicId: 'sub-dp-core',
    title: 'Episode 14: Buy Sell Stocks III',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/description/',
    difficulty: 'Hard',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-best-time-buy-sell-stock-iv',
    subtopicId: 'sub-dp-core',
    title: 'Episode 14: Buy Sell Stocks IV',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/description/',
    difficulty: 'Hard',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 30,
    frequency: 50,
    companyTags: []
  },
  {
    id: 'prob-min-cost-cut-stick',
    subtopicId: 'sub-dp-core',
    title: 'Episode 15: MIn cost to cut stick',
    platform: 'LeetCode',
    link: 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/',
    difficulty: 'Hard',
    pattern: 'DP (Dynamic Programming)',
    status: 'New',
    box: 1,
    ease: 2.5,
    interval: 0,
    nextReview: null,
    lastSolved: null,
    masteryScore: 0,
    estimatedTime: 35,
    frequency: 50,
    companyTags: []
  }
];
